version: '3.8'
services:
    employe-api-server:
        container_name: employeeapi
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 1337:8888
        networks:
            - spring-cloud-network
        image: employeeapi:latest
networks:
    spring-cloud-network:
        driver: bridge